version: 3;
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TOKEN=${TOKEN}
        - DATABASE=${DATABASE}
        - LEVEL=${LEVEL}
        - PROD=${PROD}
        - ENV_FILE=${ENV_FILE}
    volumes:
      - ./logs:/usr/bot/logs
      - ./db.sqlite3:/usr/bot/db.sqlite3
    restart:
      always